/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MailboxService } from "../mailbox.service";
import { MailboxCreateInput } from "./MailboxCreateInput";
import { Mailbox } from "./Mailbox";
import { MailboxFindManyArgs } from "./MailboxFindManyArgs";
import { MailboxWhereUniqueInput } from "./MailboxWhereUniqueInput";
import { MailboxUpdateInput } from "./MailboxUpdateInput";
import { EmailFindManyArgs } from "../../email/base/EmailFindManyArgs";
import { Email } from "../../email/base/Email";
import { EmailWhereUniqueInput } from "../../email/base/EmailWhereUniqueInput";

export class MailboxControllerBase {
  constructor(protected readonly service: MailboxService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mailbox })
  async createMailbox(
    @common.Body() data: MailboxCreateInput
  ): Promise<Mailbox> {
    return await this.service.createMailbox({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        mailboxName: true,
        synced: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Mailbox] })
  @ApiNestedQuery(MailboxFindManyArgs)
  async mailboxes(@common.Req() request: Request): Promise<Mailbox[]> {
    const args = plainToClass(MailboxFindManyArgs, request.query);
    return this.service.mailboxes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        mailboxName: true,
        synced: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mailbox })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mailbox(
    @common.Param() params: MailboxWhereUniqueInput
  ): Promise<Mailbox | null> {
    const result = await this.service.mailbox({
      where: params,
      select: {
        createdAt: true,
        id: true,
        mailboxName: true,
        synced: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mailbox })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMailbox(
    @common.Param() params: MailboxWhereUniqueInput,
    @common.Body() data: MailboxUpdateInput
  ): Promise<Mailbox | null> {
    try {
      return await this.service.updateMailbox({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          mailboxName: true,
          synced: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mailbox })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMailbox(
    @common.Param() params: MailboxWhereUniqueInput
  ): Promise<Mailbox | null> {
    try {
      return await this.service.deleteMailbox({
        where: params,
        select: {
          createdAt: true,
          id: true,
          mailboxName: true,
          synced: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/emails")
  @ApiNestedQuery(EmailFindManyArgs)
  async findEmails(
    @common.Req() request: Request,
    @common.Param() params: MailboxWhereUniqueInput
  ): Promise<Email[]> {
    const query = plainToClass(EmailFindManyArgs, request.query);
    const results = await this.service.findEmails(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        isFlagged: true,
        isRead: true,

        mailbox: {
          select: {
            id: true,
          },
        },

        receivedAt: true,
        senderEmail: true,
        senderName: true,
        subject: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/emails")
  async connectEmails(
    @common.Param() params: MailboxWhereUniqueInput,
    @common.Body() body: EmailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emails: {
        connect: body,
      },
    };
    await this.service.updateMailbox({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/emails")
  async updateEmails(
    @common.Param() params: MailboxWhereUniqueInput,
    @common.Body() body: EmailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emails: {
        set: body,
      },
    };
    await this.service.updateMailbox({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/emails")
  async disconnectEmails(
    @common.Param() params: MailboxWhereUniqueInput,
    @common.Body() body: EmailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      emails: {
        disconnect: body,
      },
    };
    await this.service.updateMailbox({
      where: params,
      data,
      select: { id: true },
    });
  }
}
